// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation-price.proto

// Protobuf Java Version: 3.25.3
package org.example.reservationprice;

public interface PriceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PriceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 reservation_id = 1;</code>
   * @return The reservationId.
   */
  long getReservationId();

  /**
   * <code>int32 number_of_guests = 2;</code>
   * @return The numberOfGuests.
   */
  int getNumberOfGuests();

  /**
   * <pre>
   * Добавлено из самостоятельного задания №8 (расширение модели)
   * </pre>
   *
   * <code>string table_type = 3;</code>
   * @return The tableType.
   */
  java.lang.String getTableType();
  /**
   * <pre>
   * Добавлено из самостоятельного задания №8 (расширение модели)
   * </pre>
   *
   * <code>string table_type = 3;</code>
   * @return The bytes for tableType.
   */
  com.google.protobuf.ByteString
      getTableTypeBytes();

  /**
   * <pre>
   * Продолжительность в часах
   * </pre>
   *
   * <code>int32 duration_hours = 4;</code>
   * @return The durationHours.
   */
  int getDurationHours();
}
