// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation-price.proto

// Protobuf Java Version: 3.25.3
package org.example.reservationprice;

public interface PriceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PriceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 reservation_id = 1;</code>
   * @return The reservationId.
   */
  long getReservationId();

  /**
   * <code>double price = 2;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <pre>
   * "AFFORDABLE" или "EXPENSIVE"
   * </pre>
   *
   * <code>string verdict = 3;</code>
   * @return The verdict.
   */
  java.lang.String getVerdict();
  /**
   * <pre>
   * "AFFORDABLE" или "EXPENSIVE"
   * </pre>
   *
   * <code>string verdict = 3;</code>
   * @return The bytes for verdict.
   */
  com.google.protobuf.ByteString
      getVerdictBytes();
}
