// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation-price.proto

// Protobuf Java Version: 3.25.3
package org.example.reservationprice;

/**
 * <pre>
 * Запрос на обновление цены
 * </pre>
 *
 * Protobuf type {@code UpdatePriceRequest}
 */
public final class UpdatePriceRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:UpdatePriceRequest)
    UpdatePriceRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdatePriceRequest.newBuilder() to construct.
  private UpdatePriceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdatePriceRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdatePriceRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.reservationprice.ReservationPriceProto.internal_static_UpdatePriceRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.reservationprice.ReservationPriceProto.internal_static_UpdatePriceRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.reservationprice.UpdatePriceRequest.class, org.example.reservationprice.UpdatePriceRequest.Builder.class);
  }

  public static final int RESERVATION_ID_FIELD_NUMBER = 1;
  private long reservationId_ = 0L;
  /**
   * <code>int64 reservation_id = 1;</code>
   * @return The reservationId.
   */
  @java.lang.Override
  public long getReservationId() {
    return reservationId_;
  }

  public static final int NEW_NUMBER_OF_GUESTS_FIELD_NUMBER = 2;
  private int newNumberOfGuests_ = 0;
  /**
   * <code>int32 new_number_of_guests = 2;</code>
   * @return The newNumberOfGuests.
   */
  @java.lang.Override
  public int getNewNumberOfGuests() {
    return newNumberOfGuests_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (reservationId_ != 0L) {
      output.writeInt64(1, reservationId_);
    }
    if (newNumberOfGuests_ != 0) {
      output.writeInt32(2, newNumberOfGuests_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (reservationId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, reservationId_);
    }
    if (newNumberOfGuests_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, newNumberOfGuests_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.reservationprice.UpdatePriceRequest)) {
      return super.equals(obj);
    }
    org.example.reservationprice.UpdatePriceRequest other = (org.example.reservationprice.UpdatePriceRequest) obj;

    if (getReservationId()
        != other.getReservationId()) return false;
    if (getNewNumberOfGuests()
        != other.getNewNumberOfGuests()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESERVATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getReservationId());
    hash = (37 * hash) + NEW_NUMBER_OF_GUESTS_FIELD_NUMBER;
    hash = (53 * hash) + getNewNumberOfGuests();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.reservationprice.UpdatePriceRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.reservationprice.UpdatePriceRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.reservationprice.UpdatePriceRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.reservationprice.UpdatePriceRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.reservationprice.UpdatePriceRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.reservationprice.UpdatePriceRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.reservationprice.UpdatePriceRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.reservationprice.UpdatePriceRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.reservationprice.UpdatePriceRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.reservationprice.UpdatePriceRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.reservationprice.UpdatePriceRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.reservationprice.UpdatePriceRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.reservationprice.UpdatePriceRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Запрос на обновление цены
   * </pre>
   *
   * Protobuf type {@code UpdatePriceRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UpdatePriceRequest)
      org.example.reservationprice.UpdatePriceRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.reservationprice.ReservationPriceProto.internal_static_UpdatePriceRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.reservationprice.ReservationPriceProto.internal_static_UpdatePriceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.reservationprice.UpdatePriceRequest.class, org.example.reservationprice.UpdatePriceRequest.Builder.class);
    }

    // Construct using org.example.reservationprice.UpdatePriceRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      reservationId_ = 0L;
      newNumberOfGuests_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.reservationprice.ReservationPriceProto.internal_static_UpdatePriceRequest_descriptor;
    }

    @java.lang.Override
    public org.example.reservationprice.UpdatePriceRequest getDefaultInstanceForType() {
      return org.example.reservationprice.UpdatePriceRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.reservationprice.UpdatePriceRequest build() {
      org.example.reservationprice.UpdatePriceRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.reservationprice.UpdatePriceRequest buildPartial() {
      org.example.reservationprice.UpdatePriceRequest result = new org.example.reservationprice.UpdatePriceRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.example.reservationprice.UpdatePriceRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.reservationId_ = reservationId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.newNumberOfGuests_ = newNumberOfGuests_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.reservationprice.UpdatePriceRequest) {
        return mergeFrom((org.example.reservationprice.UpdatePriceRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.reservationprice.UpdatePriceRequest other) {
      if (other == org.example.reservationprice.UpdatePriceRequest.getDefaultInstance()) return this;
      if (other.getReservationId() != 0L) {
        setReservationId(other.getReservationId());
      }
      if (other.getNewNumberOfGuests() != 0) {
        setNewNumberOfGuests(other.getNewNumberOfGuests());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              reservationId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              newNumberOfGuests_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long reservationId_ ;
    /**
     * <code>int64 reservation_id = 1;</code>
     * @return The reservationId.
     */
    @java.lang.Override
    public long getReservationId() {
      return reservationId_;
    }
    /**
     * <code>int64 reservation_id = 1;</code>
     * @param value The reservationId to set.
     * @return This builder for chaining.
     */
    public Builder setReservationId(long value) {

      reservationId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 reservation_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReservationId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      reservationId_ = 0L;
      onChanged();
      return this;
    }

    private int newNumberOfGuests_ ;
    /**
     * <code>int32 new_number_of_guests = 2;</code>
     * @return The newNumberOfGuests.
     */
    @java.lang.Override
    public int getNewNumberOfGuests() {
      return newNumberOfGuests_;
    }
    /**
     * <code>int32 new_number_of_guests = 2;</code>
     * @param value The newNumberOfGuests to set.
     * @return This builder for chaining.
     */
    public Builder setNewNumberOfGuests(int value) {

      newNumberOfGuests_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 new_number_of_guests = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNewNumberOfGuests() {
      bitField0_ = (bitField0_ & ~0x00000002);
      newNumberOfGuests_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:UpdatePriceRequest)
  }

  // @@protoc_insertion_point(class_scope:UpdatePriceRequest)
  private static final org.example.reservationprice.UpdatePriceRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.reservationprice.UpdatePriceRequest();
  }

  public static org.example.reservationprice.UpdatePriceRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdatePriceRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdatePriceRequest>() {
    @java.lang.Override
    public UpdatePriceRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UpdatePriceRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdatePriceRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.reservationprice.UpdatePriceRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

