// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation-price.proto

// Protobuf Java Version: 3.25.3
package org.example.reservationprice;

/**
 * <pre>
 * Ответ с ценой
 * </pre>
 *
 * Protobuf type {@code PriceResponse}
 */
public final class PriceResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PriceResponse)
    PriceResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PriceResponse.newBuilder() to construct.
  private PriceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PriceResponse() {
    verdict_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PriceResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.reservationprice.ReservationPriceProto.internal_static_PriceResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.reservationprice.ReservationPriceProto.internal_static_PriceResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.reservationprice.PriceResponse.class, org.example.reservationprice.PriceResponse.Builder.class);
  }

  public static final int RESERVATION_ID_FIELD_NUMBER = 1;
  private long reservationId_ = 0L;
  /**
   * <code>int64 reservation_id = 1;</code>
   * @return The reservationId.
   */
  @java.lang.Override
  public long getReservationId() {
    return reservationId_;
  }

  public static final int PRICE_FIELD_NUMBER = 2;
  private double price_ = 0D;
  /**
   * <code>double price = 2;</code>
   * @return The price.
   */
  @java.lang.Override
  public double getPrice() {
    return price_;
  }

  public static final int VERDICT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object verdict_ = "";
  /**
   * <pre>
   * "AFFORDABLE" или "EXPENSIVE"
   * </pre>
   *
   * <code>string verdict = 3;</code>
   * @return The verdict.
   */
  @java.lang.Override
  public java.lang.String getVerdict() {
    java.lang.Object ref = verdict_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      verdict_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "AFFORDABLE" или "EXPENSIVE"
   * </pre>
   *
   * <code>string verdict = 3;</code>
   * @return The bytes for verdict.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVerdictBytes() {
    java.lang.Object ref = verdict_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      verdict_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (reservationId_ != 0L) {
      output.writeInt64(1, reservationId_);
    }
    if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
      output.writeDouble(2, price_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(verdict_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, verdict_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (reservationId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, reservationId_);
    }
    if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, price_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(verdict_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, verdict_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.reservationprice.PriceResponse)) {
      return super.equals(obj);
    }
    org.example.reservationprice.PriceResponse other = (org.example.reservationprice.PriceResponse) obj;

    if (getReservationId()
        != other.getReservationId()) return false;
    if (java.lang.Double.doubleToLongBits(getPrice())
        != java.lang.Double.doubleToLongBits(
            other.getPrice())) return false;
    if (!getVerdict()
        .equals(other.getVerdict())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESERVATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getReservationId());
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPrice()));
    hash = (37 * hash) + VERDICT_FIELD_NUMBER;
    hash = (53 * hash) + getVerdict().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.reservationprice.PriceResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.reservationprice.PriceResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.reservationprice.PriceResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.reservationprice.PriceResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.reservationprice.PriceResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.reservationprice.PriceResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.reservationprice.PriceResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.reservationprice.PriceResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.reservationprice.PriceResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.reservationprice.PriceResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.reservationprice.PriceResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.reservationprice.PriceResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.reservationprice.PriceResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Ответ с ценой
   * </pre>
   *
   * Protobuf type {@code PriceResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PriceResponse)
      org.example.reservationprice.PriceResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.reservationprice.ReservationPriceProto.internal_static_PriceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.reservationprice.ReservationPriceProto.internal_static_PriceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.reservationprice.PriceResponse.class, org.example.reservationprice.PriceResponse.Builder.class);
    }

    // Construct using org.example.reservationprice.PriceResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      reservationId_ = 0L;
      price_ = 0D;
      verdict_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.reservationprice.ReservationPriceProto.internal_static_PriceResponse_descriptor;
    }

    @java.lang.Override
    public org.example.reservationprice.PriceResponse getDefaultInstanceForType() {
      return org.example.reservationprice.PriceResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.reservationprice.PriceResponse build() {
      org.example.reservationprice.PriceResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.reservationprice.PriceResponse buildPartial() {
      org.example.reservationprice.PriceResponse result = new org.example.reservationprice.PriceResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.example.reservationprice.PriceResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.reservationId_ = reservationId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.price_ = price_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.verdict_ = verdict_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.reservationprice.PriceResponse) {
        return mergeFrom((org.example.reservationprice.PriceResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.reservationprice.PriceResponse other) {
      if (other == org.example.reservationprice.PriceResponse.getDefaultInstance()) return this;
      if (other.getReservationId() != 0L) {
        setReservationId(other.getReservationId());
      }
      if (other.getPrice() != 0D) {
        setPrice(other.getPrice());
      }
      if (!other.getVerdict().isEmpty()) {
        verdict_ = other.verdict_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              reservationId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 17: {
              price_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 26: {
              verdict_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long reservationId_ ;
    /**
     * <code>int64 reservation_id = 1;</code>
     * @return The reservationId.
     */
    @java.lang.Override
    public long getReservationId() {
      return reservationId_;
    }
    /**
     * <code>int64 reservation_id = 1;</code>
     * @param value The reservationId to set.
     * @return This builder for chaining.
     */
    public Builder setReservationId(long value) {

      reservationId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 reservation_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReservationId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      reservationId_ = 0L;
      onChanged();
      return this;
    }

    private double price_ ;
    /**
     * <code>double price = 2;</code>
     * @return The price.
     */
    @java.lang.Override
    public double getPrice() {
      return price_;
    }
    /**
     * <code>double price = 2;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(double value) {

      price_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double price = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      bitField0_ = (bitField0_ & ~0x00000002);
      price_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object verdict_ = "";
    /**
     * <pre>
     * "AFFORDABLE" или "EXPENSIVE"
     * </pre>
     *
     * <code>string verdict = 3;</code>
     * @return The verdict.
     */
    public java.lang.String getVerdict() {
      java.lang.Object ref = verdict_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        verdict_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "AFFORDABLE" или "EXPENSIVE"
     * </pre>
     *
     * <code>string verdict = 3;</code>
     * @return The bytes for verdict.
     */
    public com.google.protobuf.ByteString
        getVerdictBytes() {
      java.lang.Object ref = verdict_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        verdict_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "AFFORDABLE" или "EXPENSIVE"
     * </pre>
     *
     * <code>string verdict = 3;</code>
     * @param value The verdict to set.
     * @return This builder for chaining.
     */
    public Builder setVerdict(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      verdict_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "AFFORDABLE" или "EXPENSIVE"
     * </pre>
     *
     * <code>string verdict = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearVerdict() {
      verdict_ = getDefaultInstance().getVerdict();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "AFFORDABLE" или "EXPENSIVE"
     * </pre>
     *
     * <code>string verdict = 3;</code>
     * @param value The bytes for verdict to set.
     * @return This builder for chaining.
     */
    public Builder setVerdictBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      verdict_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PriceResponse)
  }

  // @@protoc_insertion_point(class_scope:PriceResponse)
  private static final org.example.reservationprice.PriceResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.reservationprice.PriceResponse();
  }

  public static org.example.reservationprice.PriceResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PriceResponse>
      PARSER = new com.google.protobuf.AbstractParser<PriceResponse>() {
    @java.lang.Override
    public PriceResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PriceResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PriceResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.reservationprice.PriceResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

