// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation-price.proto

// Protobuf Java Version: 3.25.3
package org.example.reservationprice;

/**
 * <pre>
 * Запрос на расчет цены
 * </pre>
 *
 * Protobuf type {@code PriceRequest}
 */
public final class PriceRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PriceRequest)
    PriceRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PriceRequest.newBuilder() to construct.
  private PriceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PriceRequest() {
    tableType_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PriceRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.reservationprice.ReservationPriceProto.internal_static_PriceRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.reservationprice.ReservationPriceProto.internal_static_PriceRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.reservationprice.PriceRequest.class, org.example.reservationprice.PriceRequest.Builder.class);
  }

  public static final int RESERVATION_ID_FIELD_NUMBER = 1;
  private long reservationId_ = 0L;
  /**
   * <code>int64 reservation_id = 1;</code>
   * @return The reservationId.
   */
  @java.lang.Override
  public long getReservationId() {
    return reservationId_;
  }

  public static final int NUMBER_OF_GUESTS_FIELD_NUMBER = 2;
  private int numberOfGuests_ = 0;
  /**
   * <code>int32 number_of_guests = 2;</code>
   * @return The numberOfGuests.
   */
  @java.lang.Override
  public int getNumberOfGuests() {
    return numberOfGuests_;
  }

  public static final int TABLE_TYPE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tableType_ = "";
  /**
   * <pre>
   * Добавлено из самостоятельного задания №8 (расширение модели)
   * </pre>
   *
   * <code>string table_type = 3;</code>
   * @return The tableType.
   */
  @java.lang.Override
  public java.lang.String getTableType() {
    java.lang.Object ref = tableType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tableType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Добавлено из самостоятельного задания №8 (расширение модели)
   * </pre>
   *
   * <code>string table_type = 3;</code>
   * @return The bytes for tableType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTableTypeBytes() {
    java.lang.Object ref = tableType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tableType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DURATION_HOURS_FIELD_NUMBER = 4;
  private int durationHours_ = 0;
  /**
   * <pre>
   * Продолжительность в часах
   * </pre>
   *
   * <code>int32 duration_hours = 4;</code>
   * @return The durationHours.
   */
  @java.lang.Override
  public int getDurationHours() {
    return durationHours_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (reservationId_ != 0L) {
      output.writeInt64(1, reservationId_);
    }
    if (numberOfGuests_ != 0) {
      output.writeInt32(2, numberOfGuests_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tableType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, tableType_);
    }
    if (durationHours_ != 0) {
      output.writeInt32(4, durationHours_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (reservationId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, reservationId_);
    }
    if (numberOfGuests_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, numberOfGuests_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tableType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, tableType_);
    }
    if (durationHours_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, durationHours_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.reservationprice.PriceRequest)) {
      return super.equals(obj);
    }
    org.example.reservationprice.PriceRequest other = (org.example.reservationprice.PriceRequest) obj;

    if (getReservationId()
        != other.getReservationId()) return false;
    if (getNumberOfGuests()
        != other.getNumberOfGuests()) return false;
    if (!getTableType()
        .equals(other.getTableType())) return false;
    if (getDurationHours()
        != other.getDurationHours()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESERVATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getReservationId());
    hash = (37 * hash) + NUMBER_OF_GUESTS_FIELD_NUMBER;
    hash = (53 * hash) + getNumberOfGuests();
    hash = (37 * hash) + TABLE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getTableType().hashCode();
    hash = (37 * hash) + DURATION_HOURS_FIELD_NUMBER;
    hash = (53 * hash) + getDurationHours();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.reservationprice.PriceRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.reservationprice.PriceRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.reservationprice.PriceRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.reservationprice.PriceRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.reservationprice.PriceRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.reservationprice.PriceRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.reservationprice.PriceRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.reservationprice.PriceRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.reservationprice.PriceRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.reservationprice.PriceRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.reservationprice.PriceRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.reservationprice.PriceRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.reservationprice.PriceRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Запрос на расчет цены
   * </pre>
   *
   * Protobuf type {@code PriceRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PriceRequest)
      org.example.reservationprice.PriceRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.reservationprice.ReservationPriceProto.internal_static_PriceRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.reservationprice.ReservationPriceProto.internal_static_PriceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.reservationprice.PriceRequest.class, org.example.reservationprice.PriceRequest.Builder.class);
    }

    // Construct using org.example.reservationprice.PriceRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      reservationId_ = 0L;
      numberOfGuests_ = 0;
      tableType_ = "";
      durationHours_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.reservationprice.ReservationPriceProto.internal_static_PriceRequest_descriptor;
    }

    @java.lang.Override
    public org.example.reservationprice.PriceRequest getDefaultInstanceForType() {
      return org.example.reservationprice.PriceRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.reservationprice.PriceRequest build() {
      org.example.reservationprice.PriceRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.reservationprice.PriceRequest buildPartial() {
      org.example.reservationprice.PriceRequest result = new org.example.reservationprice.PriceRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.example.reservationprice.PriceRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.reservationId_ = reservationId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.numberOfGuests_ = numberOfGuests_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.tableType_ = tableType_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.durationHours_ = durationHours_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.reservationprice.PriceRequest) {
        return mergeFrom((org.example.reservationprice.PriceRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.reservationprice.PriceRequest other) {
      if (other == org.example.reservationprice.PriceRequest.getDefaultInstance()) return this;
      if (other.getReservationId() != 0L) {
        setReservationId(other.getReservationId());
      }
      if (other.getNumberOfGuests() != 0) {
        setNumberOfGuests(other.getNumberOfGuests());
      }
      if (!other.getTableType().isEmpty()) {
        tableType_ = other.tableType_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getDurationHours() != 0) {
        setDurationHours(other.getDurationHours());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              reservationId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              numberOfGuests_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              tableType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              durationHours_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long reservationId_ ;
    /**
     * <code>int64 reservation_id = 1;</code>
     * @return The reservationId.
     */
    @java.lang.Override
    public long getReservationId() {
      return reservationId_;
    }
    /**
     * <code>int64 reservation_id = 1;</code>
     * @param value The reservationId to set.
     * @return This builder for chaining.
     */
    public Builder setReservationId(long value) {

      reservationId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 reservation_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReservationId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      reservationId_ = 0L;
      onChanged();
      return this;
    }

    private int numberOfGuests_ ;
    /**
     * <code>int32 number_of_guests = 2;</code>
     * @return The numberOfGuests.
     */
    @java.lang.Override
    public int getNumberOfGuests() {
      return numberOfGuests_;
    }
    /**
     * <code>int32 number_of_guests = 2;</code>
     * @param value The numberOfGuests to set.
     * @return This builder for chaining.
     */
    public Builder setNumberOfGuests(int value) {

      numberOfGuests_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 number_of_guests = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumberOfGuests() {
      bitField0_ = (bitField0_ & ~0x00000002);
      numberOfGuests_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object tableType_ = "";
    /**
     * <pre>
     * Добавлено из самостоятельного задания №8 (расширение модели)
     * </pre>
     *
     * <code>string table_type = 3;</code>
     * @return The tableType.
     */
    public java.lang.String getTableType() {
      java.lang.Object ref = tableType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Добавлено из самостоятельного задания №8 (расширение модели)
     * </pre>
     *
     * <code>string table_type = 3;</code>
     * @return The bytes for tableType.
     */
    public com.google.protobuf.ByteString
        getTableTypeBytes() {
      java.lang.Object ref = tableType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Добавлено из самостоятельного задания №8 (расширение модели)
     * </pre>
     *
     * <code>string table_type = 3;</code>
     * @param value The tableType to set.
     * @return This builder for chaining.
     */
    public Builder setTableType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tableType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Добавлено из самостоятельного задания №8 (расширение модели)
     * </pre>
     *
     * <code>string table_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTableType() {
      tableType_ = getDefaultInstance().getTableType();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Добавлено из самостоятельного задания №8 (расширение модели)
     * </pre>
     *
     * <code>string table_type = 3;</code>
     * @param value The bytes for tableType to set.
     * @return This builder for chaining.
     */
    public Builder setTableTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tableType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int durationHours_ ;
    /**
     * <pre>
     * Продолжительность в часах
     * </pre>
     *
     * <code>int32 duration_hours = 4;</code>
     * @return The durationHours.
     */
    @java.lang.Override
    public int getDurationHours() {
      return durationHours_;
    }
    /**
     * <pre>
     * Продолжительность в часах
     * </pre>
     *
     * <code>int32 duration_hours = 4;</code>
     * @param value The durationHours to set.
     * @return This builder for chaining.
     */
    public Builder setDurationHours(int value) {

      durationHours_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Продолжительность в часах
     * </pre>
     *
     * <code>int32 duration_hours = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDurationHours() {
      bitField0_ = (bitField0_ & ~0x00000008);
      durationHours_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PriceRequest)
  }

  // @@protoc_insertion_point(class_scope:PriceRequest)
  private static final org.example.reservationprice.PriceRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.reservationprice.PriceRequest();
  }

  public static org.example.reservationprice.PriceRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PriceRequest>
      PARSER = new com.google.protobuf.AbstractParser<PriceRequest>() {
    @java.lang.Override
    public PriceRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PriceRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PriceRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.reservationprice.PriceRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

