// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation-price.proto

// Protobuf Java Version: 3.25.3
package org.example.reservationprice;

public final class ReservationPriceProto {
  private ReservationPriceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PriceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PriceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PriceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PriceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdatePriceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdatePriceRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027reservation-price.proto\"l\n\014PriceReques" +
      "t\022\026\n\016reservation_id\030\001 \001(\003\022\030\n\020number_of_g" +
      "uests\030\002 \001(\005\022\022\n\ntable_type\030\003 \001(\t\022\026\n\016durat" +
      "ion_hours\030\004 \001(\005\"G\n\rPriceResponse\022\026\n\016rese" +
      "rvation_id\030\001 \001(\003\022\r\n\005price\030\002 \001(\001\022\017\n\007verdi" +
      "ct\030\003 \001(\t\"J\n\022UpdatePriceRequest\022\026\n\016reserv" +
      "ation_id\030\001 \001(\003\022\034\n\024new_number_of_guests\030\002" +
      " \001(\0052\202\001\n\027ReservationPriceService\0221\n\016Calc" +
      "ulatePrice\022\r.PriceRequest\032\016.PriceRespons" +
      "e\"\000\0224\n\013UpdatePrice\022\023.UpdatePriceRequest\032" +
      "\016.PriceResponse\"\000B7\n\034org.example.reserva" +
      "tionpriceB\025ReservationPriceProtoP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PriceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PriceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PriceRequest_descriptor,
        new java.lang.String[] { "ReservationId", "NumberOfGuests", "TableType", "DurationHours", });
    internal_static_PriceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PriceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PriceResponse_descriptor,
        new java.lang.String[] { "ReservationId", "Price", "Verdict", });
    internal_static_UpdatePriceRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UpdatePriceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdatePriceRequest_descriptor,
        new java.lang.String[] { "ReservationId", "NewNumberOfGuests", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
