// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation-price.proto

// Protobuf Java Version: 3.25.3
package org.example.reservationprice;

public interface UpdatePriceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdatePriceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 reservation_id = 1;</code>
   * @return The reservationId.
   */
  long getReservationId();

  /**
   * <code>int32 new_number_of_guests = 2;</code>
   * @return The newNumberOfGuests.
   */
  int getNewNumberOfGuests();
}
